### Сергей Поздняков

**@Матвей_Шмонов**, Если Вы используете исключения при проверке условий,
то проверяющая функция уже может ничего не возвращать. Само исключение
уже является кодом ошибки и доказательством того, что что-то пошло не
так. Более того, если Вы выбрасываете исключение, то блок
`if self.check_name(name):` так ничего и не проверит, поскольку выполнение
программы начнёт идти в блоках `except:` и `finally:`, минуя обычные блоки
программы.

Обычно если проверяющие функции возвращают коды ошибки или `True` - `False`
через `Return`, то в них исключения не используются.
